### ISSUE TITLE
I don't see Elastic search Installed in the Architecture Diagram

### ISSUE THREAD

**Issue by satishkovuru** [chhatbarjignesh/reportportal-aws-cfn#5]
Hi I am in initial stages of Report Portal cloud Migration and Needed more information, Is there a way to configure Elastic Search RabbitMQ in here directly from docker-compose.yaml?

**Comment by chhatbarjignesh** [comment]
No currently, It will create containers of elasticsearch and rabbitmq on the ec2 instance. If you want, you can create a PR that will create elasticsearch and AmazonMQ clusters.

Enhancement is always welcome

**Comment by satishkovuru** [comment]
Thank you for the information
